camunda.bpm:
  webapp:
    index-redirect-enabled: true
  admin-user:
    id: admin
    password: admin

user.timezone: GMT+02:00



### GMX DB old
# spring:
#  datasource:
#    maxActive: 1
#    url: jdbc:postgresql://ec2-54-75-249-162.eu-west-1.compute.amazonaws.com:5432/dea2li9qvvs6e4?sslmode=require&user=ucxhvwaujfziup&password=23f43414d44152563df28db7b1787b2556c4b353780152fb6ff1eae536fe9dc2
#    username: ucxhvwaujfziup
#    password: 23f43414d44152563df28db7b1787b2556c4b353780152fb6ff1eae536fe9dc2
#    driverClassName: org.postgresql.Driver

spring:
  datasource:
    maxActive: 1
    url: jdbc:postgresql://ec2-54-243-252-91.compute-1.amazonaws.com:5432/d52imn0hvjaehu?sslmode=require&user=nzntlehjqwzxlp&password=44e3e8ea3d41db6da2fb60164064fb876f8f462d09abebfe04cff98b67d1e3a0
    username: nzntlehjqwzxlp
    password: 44e3e8ea3d41db6da2fb60164064fb876f8f462d09abebfe04cff98b67d1e3a0
    driverClassName: org.postgresql.Driver

    